/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StormPrepRouteImport } from './routes/storm-prep'
import { Route as ScamAlertsRouteImport } from './routes/scam-alerts'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnalysisTypeRouteImport } from './routes/analysis/$type'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountSavedRouteImport } from './routes/account/saved'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountHistoryRouteImport } from './routes/account/history'
import { Route as ResourcesCategoryCategoryRouteImport } from './routes/resources/category.$category'
import { Route as ResourcesArticleSlugRouteImport } from './routes/resources/article.$slug'

const StormPrepRoute = StormPrepRouteImport.update({
  id: '/storm-prep',
  path: '/storm-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamAlertsRoute = ScamAlertsRouteImport.update({
  id: '/scam-alerts',
  path: '/scam-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisTypeRoute = AnalysisTypeRouteImport.update({
  id: '/analysis/$type',
  path: '/analysis/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSavedRoute = AccountSavedRouteImport.update({
  id: '/account/saved',
  path: '/account/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/account/history',
  path: '/account/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCategoryCategoryRoute =
  ResourcesCategoryCategoryRouteImport.update({
    id: '/resources/category/$category',
    path: '/resources/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesArticleSlugRoute = ResourcesArticleSlugRouteImport.update({
  id: '/resources/article/$slug',
  path: '/resources/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scam-alerts': typeof ScamAlertsRoute
  '/storm-prep': typeof StormPrepRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/analysis/$type': typeof AnalysisTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/account/': typeof AccountIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scam-alerts': typeof ScamAlertsRoute
  '/storm-prep': typeof StormPrepRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/analysis/$type': typeof AnalysisTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/account': typeof AccountIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/dashboard': typeof DashboardRoute
  '/directory': typeof DirectoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scam-alerts': typeof ScamAlertsRoute
  '/storm-prep': typeof StormPrepRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/saved': typeof AccountSavedRoute
  '/account/settings': typeof AccountSettingsRoute
  '/analysis/$type': typeof AnalysisTypeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/account/': typeof AccountIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/resources/article/$slug': typeof ResourcesArticleSlugRoute
  '/resources/category/$category': typeof ResourcesCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/directory'
    | '/onboarding'
    | '/scam-alerts'
    | '/storm-prep'
    | '/account/history'
    | '/account/notifications'
    | '/account/saved'
    | '/account/settings'
    | '/analysis/$type'
    | '/auth/login'
    | '/auth/signup'
    | '/account/'
    | '/resources/'
    | '/resources/article/$slug'
    | '/resources/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/directory'
    | '/onboarding'
    | '/scam-alerts'
    | '/storm-prep'
    | '/account/history'
    | '/account/notifications'
    | '/account/saved'
    | '/account/settings'
    | '/analysis/$type'
    | '/auth/login'
    | '/auth/signup'
    | '/account'
    | '/resources'
    | '/resources/article/$slug'
    | '/resources/category/$category'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/dashboard'
    | '/directory'
    | '/onboarding'
    | '/scam-alerts'
    | '/storm-prep'
    | '/account/history'
    | '/account/notifications'
    | '/account/saved'
    | '/account/settings'
    | '/analysis/$type'
    | '/auth/login'
    | '/auth/signup'
    | '/account/'
    | '/resources/'
    | '/resources/article/$slug'
    | '/resources/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  DashboardRoute: typeof DashboardRoute
  DirectoryRoute: typeof DirectoryRoute
  OnboardingRoute: typeof OnboardingRoute
  ScamAlertsRoute: typeof ScamAlertsRoute
  StormPrepRoute: typeof StormPrepRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountSavedRoute: typeof AccountSavedRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AnalysisTypeRoute: typeof AnalysisTypeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesArticleSlugRoute: typeof ResourcesArticleSlugRoute
  ResourcesCategoryCategoryRoute: typeof ResourcesCategoryCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storm-prep': {
      id: '/storm-prep'
      path: '/storm-prep'
      fullPath: '/storm-prep'
      preLoaderRoute: typeof StormPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-alerts': {
      id: '/scam-alerts'
      path: '/scam-alerts'
      fullPath: '/scam-alerts'
      preLoaderRoute: typeof ScamAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$type': {
      id: '/analysis/$type'
      path: '/analysis/$type'
      fullPath: '/analysis/$type'
      preLoaderRoute: typeof AnalysisTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/saved': {
      id: '/account/saved'
      path: '/account/saved'
      fullPath: '/account/saved'
      preLoaderRoute: typeof AccountSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/history': {
      id: '/account/history'
      path: '/account/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/category/$category': {
      id: '/resources/category/$category'
      path: '/resources/category/$category'
      fullPath: '/resources/category/$category'
      preLoaderRoute: typeof ResourcesCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/article/$slug': {
      id: '/resources/article/$slug'
      path: '/resources/article/$slug'
      fullPath: '/resources/article/$slug'
      preLoaderRoute: typeof ResourcesArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  DashboardRoute: DashboardRoute,
  DirectoryRoute: DirectoryRoute,
  OnboardingRoute: OnboardingRoute,
  ScamAlertsRoute: ScamAlertsRoute,
  StormPrepRoute: StormPrepRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountSavedRoute: AccountSavedRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AnalysisTypeRoute: AnalysisTypeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AccountIndexRoute: AccountIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesArticleSlugRoute: ResourcesArticleSlugRoute,
  ResourcesCategoryCategoryRoute: ResourcesCategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
